const banks = [
  {
    bankName: "bitstamp",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 80000,
    dailyMax: 80000,
    maxAge: 50,
    jointAccount: true,
    bankStatement: true,
    passport: false,
    id: false,
    driverLicense: false,
    ub: false,
    camera: true,
    image:
      "https://www.blockchainwg.eu/wp-content/uploads/2017/11/Bitstamp-400x200.png",
  },
  {
    bankName: "kraken",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 10000000,
    dailyMax: 100000000,
    maxAge: 55,
    jointAccount: true,
    bankStatement: false,
    passport: false,
    id: false,
    driverLicense: false,
    ub: true,
    camera: false,
    image:
      "https://lh3.googleusercontent.com/proxy/pAYfNvzrDjT0yb0SAOMWpd327I28u3zrmJey7JNftbopRx4xs--RldCBbHLYv7xHHtAuSKfu8r7rlPDmpe4MH4WVPyrNxFLTZ-A6s1xY6PPw8kaRxCFPYOtGmYy-5Mf1Pey2gXCtQpGp6mkdmZ_c3_F3s2YSR0zQZ7yWGs_stHT0nrc",
  },
  {
    bankName: "simplex",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 50000,
    dailyMax: 20000,
    maxAge: 100,
    jointAccount: true,
    bankStatement: true,
    passport: true,
    id: true,
    driverLicense: false,
    ub: false,
    camera: true,
    image:
      "https://www.bitdegree.org/crypto/storage/media/images/simplex-review-logo-big.o.png",
  },
  {
    bankName: "coinmetro",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 500000,
    dailyMax: 1000000,
    maxAge: 100,
    jointAccount: true,
    bankStatement: true,
    passport: false,
    id: false,
    driverLicense: false,
    ub: false,
    camera: true,
    image:
      "https://cdn.shopify.com/s/files/1/0381/5912/2476/files/cm_logo_ccolors_800x.png?v=1595700201",
  },
  {
    bankName: "ftx",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 1000000,
    dailyMax: 100000,
    maxAge: 100,
    jointAccount: false,
    bankStatement: false,
    passport: false,
    id: false,
    driverLicense: false,
    ub: false,
    camera: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/FTX_log.png",
  },
  {
    bankName: "bitfinex",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 1000000,
    dailyMax: 100000,
    maxAge: 100,
    jointAccount: false,
    bankStatement: false,
    passport: false,
    id: false,
    driverLicense: false,
    ub: true,
    camera: false,
    image: "https://download.logo.wine/logo/Bitfinex/Bitfinex-Logo.wine.png",
  },
  {
    bankName: "btcdirect",
    resFromDE: {
      sparkasse: "sparkasse",
      ing: "ing",
      dkb: "dkb",
      ing: "ing",
      raifeisenbank: "raifeisenbank",
      waiserbank: "waiserbank",
      none: "none",
    },
    gender: {
      male: "male",
      female: "female",
    },
    country: {
      germany: "germany",
      austria: "austria",
    },
    mounthMax: 50000,
    dailyMax: 50000,
    maxAge: 100,
    jointAccount: false,
    bankStatement: false,
    passport: true,
    id: true,
    driverLicense: false,
    ub: true,
    camera: false,
    image:
      "https://airdroplibrary.com/wp-content/uploads/2019/07/btcdirect-exchange-logo.png",
  },
];

export default banks;
